### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by mlconnor** [gadelkareem/sails-dynamodb#19]
Having fun with this module so far.  Is there a way to show the query being run against DynamoDB so that I can tell whether it is running full table scans or using the index?  I just want to make sure that my queries will scale when we get a lot of data in the tables.

I see that with SQL databases using can use query() and with MongoDB you can use the native() method.

**Comment by devinivy** [comment]
Glad!  This module is fairly young, so we appreciate you using it and bringing up issues like this one.  There is currently no logging mechanism, and there's no `.query()` equivalent, but if you have a suggestion we could approve a proper feature request and accept a PR for it.

I will add that I was careful to use an index whenever possible!  Feel free to dig into the code to see how this works.

**Comment by mlconnor** [comment]
Ok thanks @devinivy.  I could tell that you thought through performance and indexing.  I was more worried about the setup on my end being correct.  Nice module, thanks for supporting it.
