### ISSUE TITLE
Is project active?

### ISSUE THREAD

**Issue by oiramalli** [gadelkareem/sails-dynamodb#32]
Hi, I was trying to use an adapter for dynamodb-waterline, and I saw that this is using vogel, but it's really outdated, is this project still active??

**Comment by devinivy** [comment]
I don't actively maintain this– you might ask @gadelkareem or go ahead and fork it!  As I find time I try to field issues, but it's not terribly often.

**Comment by oiramalli** [comment]
Thank's for the quick reply. I will keep looking, because I'm kinda short on my deadline.
