### ISSUE TITLE
Publish current version as v0.12.0

### ISSUE THREAD

**Issue by devinivy** [gadelkareem/sails-dynamodb#5]
@gadelkareem there have been a lot of changes, and I know in #4 there was a request to publish the current version of the adapter.  Can we bump the version and publish to npm?

**Comment by gadelkareem** [comment]
npm v0.12.0 published and you can now publish npm next releases as an owner. Let me know if you need any help

**Comment by devinivy** [comment]
Sure!  My info is,

> devinivy devin@bigroomstudios.com
